[package]
name = "gfx-backend-metal"
version = "0.1.0"
description = "Metal API backend for gfx-rs"
homepage = "https://github.com/gfx-rs/gfx"
repository = "https://github.com/gfx-rs/gfx"
keywords = ["graphics", "gamedev"]
license = "MIT OR Apache-2.0"
authors = ["The Gfx-rs Developers"]
readme = "README.md"
documentation = "https://docs.rs/gfx-backend-metal"
workspace = "../../.."

[features]
default = ["winit"]
auto-capture = []

[lib]
name = "gfx_backend_metal"

[dependencies]
gfx-hal = { path = "../../hal", version = "0.1" }
bitflags = "1.0"
log = { version = "0.4", features = ["release_max_level_error"] }
#Current upstream: 0.17
winit = { git = "https://github.com/jTitor/winit", version = "^0.17", optional = true }

dispatch = { version = "0.1", optional = true }
smallvec = "0.6"
spirv_cross = "0.11.2"
parking_lot = "0.6.3"
storage-map = "0.1.2"

#Unclear which of these aren't available
#under iOS.
[target.'cfg(any(target_os = "macos", target_os = "ios"))'.dependencies]
metal = { version = "0.13.0", features = ["private"] }
foreign-types = "0.3"
objc = "0.2.5"
block = "0.1"
cocoa = "0.18"
core-graphics = "0.17"
#unclear if still needed?
#io-surface = "0.10"
